# Generated by Django 3.1.2 on 2020-10-13 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posttab',
            options={'managed': True},
        ),
    ]
