# Generated by Django 3.1.2 on 2020-10-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201013_0543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posttab',
            options={'managed': False},
        ),
    ]
