# Generated by Django 3.1.2 on 2020-10-14 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20201014_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posttab',
            options={'managed': True},
        ),
    ]
